# -*- coding: utf-8 -*-
"""Spam_Mail_Detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2cSPMUSSHXz6rHCGZLHR0JL5XWCYPIy
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
df = pd.read_csv(
    "SMSSpamCollection",
    sep='\t',
    names=['label', 'message']
)
df.head()
print(df.shape)
print(df['label'].value_counts())
df['label'] = df['label'].map({
    'ham':0,
    'spam':1
})
df.head()
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
def preprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    words = text.split()
    words = [word for word in words if word not in stop_words]
    return " ".join(words)
df['message'] = df['message'].apply(preprocess)
df.head()
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['message'])
y = df['label']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
model = MultinomialNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print(classification_report(y_test, y_pred))
sample = [
    "Congratulations! You won a free iPhone",
]

sample = [preprocess(msg) for msg in sample]

sample_vector = vectorizer.transform(sample)

prediction = model.predict(sample_vector)

if prediction[0] == 1:
    print("Spam Mail")
else:
    print("Ham Mail")